[GTK]
application_prefer_dark_theme = true

[background]
# 必须与 greetd-wallpaper-rotator 脚本生成的路径一致
path = "/var/lib/greetd-wallpapers/wallpaper.jpg"
fit = "Cover"

[appearance]
greeting_msg = ""
show_clock = false
